# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdXkCjUW68rItdGFeyycU94RE3Z0la_j
"""

# Logistic Regression with Preprocessing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Step 2: Ask user for dataset filename
filename = input("Enter dataset filename (dataset.csv extension): ")

# Step 3: Read dataset
df = pd.read_csv("dataset.csv")
print("df")
print(df.head())

# Step 4: Drop ID column if present
if 'id' in df.columns:
    df.drop(id, axis=1)

# Step 5: Encode categorical variables
le = LabelEncoder()
df['Gender']= le.fit_transform(df['Gender'])
df['Vehicle_Age']= le.fit_transform(df['Vehicle_Age'])
df['Vehicle_Damage']= le.fit_transform(df['Vehicle_Damage'])

# Step 6: Split into features and target
X=df.drop('Response', axis=1)
y=df['Response']

# Step 7: Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 8: Train-test split (80/20)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Step 9: Train Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 10: Make predictions
y_pred = model.predict(X_test)


# Optional: Plotting
plt.figure(figsize=(6,4))
plt.scatter(range(len(y_test)), y_test, color='blue', label='Actual')
plt.scatter(range(len(y_pred)), y_pred, color='red', marker='x', label='Predicted')
plt.title("Actual vs Predicted - Logistic Regression")
plt.xlabel("Sample Index")
plt.ylabel("Response")
plt.legend()
plt.show()